#ifndef CONFIG_H
#define CONFIG_H

#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_PROGRAM_LOAD_ADDRESS 0x200
#define CHIP8_HEIGHT 32
#define CHIP8_WIDTH 64
#define EMULATOR_WINDOW_TITLE "Chip8 Emulator"
#define CHIP8_WINDOW_MULTIPLIER 10
#define CHIP8_TOTAL_DATAREGISTERS 16
#define CHIP8_TOTAL_STACK 16
#define CHIP8_TOTAL_KEYS 16
#define CHIP8_CHARACTERSET_LOADADDRESS 0x00
#define CHIP8_DEFAULT_SPRITE_HEIGHT 5

#endif